plugins {
    id 'com.android.application'
}

def releaseKeystoreFile = System.getenv("ANDROID_KEYSTORE_FILE")
def releaseKeystorePassword = System.getenv("ANDROID_KEYSTORE_PASSWORD")
def releaseKeyAlias = System.getenv("ANDROID_KEY_ALIAS")
def releaseKeyPassword = System.getenv("ANDROID_KEY_PASSWORD")

def hasReleaseSigning =
        releaseKeystoreFile &&
        releaseKeystorePassword &&
        releaseKeyAlias &&
        releaseKeyPassword

android {
    namespace 'com.krianapps.warkoppos.sgl'
    compileSdk 36

    defaultConfig {
        applicationId 'com.krianapps.warkoppos.sgl'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    signingConfigs {
        release {
            if (hasReleaseSigning) {
                storeFile file(releaseKeystoreFile)
                storePassword releaseKeystorePassword
                keyAlias releaseKeyAlias
                keyPassword releaseKeyPassword
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            if (hasReleaseSigning) {
                signingConfig signingConfigs.release
            }
        }

        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.17.0'
}